CREATE TABLE USUARIO(
    EMAIL VARCHAR(255) PRIMARY KEY CHECK(EMAIL LIKE '%@%'),
    NOME VARCHAR(255) NOT NULL,
    SENHA VARCHAR(50) NOT NULL,
    SALDO DECIMAL NOT NULL,
    CODIGO_PEDIDO INT UNIQUE,
    TIPO INT NOT NULL CHECK(TIPO = 0 OR TIPO = 1)
);

CREATE TABLE PRODUTO(
    ID_PRODUTO SERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    CATEGORIA VARCHAR(255) NOT NULL,
    PRECO DECIMAL NOT NULL,
    IMAGEM_URL TEXT NOT NULL,
    ESTOQUE INT NOT NULL
);